### ISSUE TITLE
wwtime donne toujours la même heure

### ISSUE THREAD

**Issue by tet102** [bacardi55/kalliope-wwtime#1]
Bonjour, j'ouvre une nouvelle issue. car suite installation wwtime, kalliope me donne toujours l'heure locale meme si je demande l'heure de tokyo. La ville est bien comprise, j'en ai essayé d'autres idem.

J'ai trouvé : en fait il y a conflit avec le brain systemedate. qui reponds à la question quelle heure est-il ? il faudrait corriger l'ordre du module brain_fr.yml et écrire : Donnes moi l'heure de... au lieu de quelle heure est il à ....?

**Comment by bacardi55** [comment]
Le contenu des yml et template ici n'est qu'a but indicatif. Lors de l configuration de kalliope, c'est a l'utilisateur de faire attention a ce que les différents ordres des différentes synapses ne soient pas en conflit :)

**Comment by tet102** [comment]
Excuses moi. mais je suis pas d'accord avec toi...Car un débutant qui va installer les différents modules va galérer comme moi.

**Comment by bacardi55** [comment]
Ok, même remarque que sur l'autre ticket, je mettrais a jour quand je serais sur un ordi et non un ecran de téléphone :)
(Mais j'accepte aussi les pull request sur github si tu veux proposer des modifications :))

Merci de t'intéresser a ce neuron :)

**Comment by bacardi55** [comment]
Fix with this commit: https://github.com/bacardi55/kalliope-wwtime/commit/92081b619f07f50b253225b648827a7ac38bfacd
