### ISSUE TITLE
fichier brain module wwtime. {{}} en trop.

### ISSUE THREAD

**Issue by tet102** [bacardi55/kalliope-wwtime#2]
Rebonjour, j'ai vu qu'il y avait des accolades en trop au niveau des fichiers brain.ymj et brain_fr.yml.
En effet, a chaque fois que donnais l'ordre (Donnes moi l'heure de Tokyo); j'avais un retour API key erreur.
J'ai tout simplement enlever les accolades au niveau de la ligne  gmaps_api_key: "{{Gmaps API Key}}"  et cela a marcher.
Il faudrait donc remplacer dans brain.yml et brain_fr.yml les lignes: gmaps_api_key: "{{gmaps_api_key}}" par gmaps_api_key: "gmaps_api_key"
merci

**Comment by bacardi55** [comment]
Bonjour,

Les accolades sont utilisées pour les vairiables globales (voir ici: https://github.com/kalliope-project/kalliope/blob/master/Docs/settings.md#global-variables) afin de créer des variables réutilisable plusieurs fois dans les "brains" (et aussi cela permet de le changer qu'une fois pour toutes les synapses l'utilisant :))

**Comment by tet102** [comment]
Ok mais quand on récupère les exemples on est pas à ce niveau. Je pense qu'il vaut mieux donner un exemple qui soit fonctionnel, aprés l'utilisateur averti pourra faire sa salade en attribuant une variable globale. Je suis pas d'un niveau informatique execptionnel et j'ai passé 3h à chercher l'erreur et encore j'ai eu du bol à essyer cela. Cdlt

**Comment by bacardi55** [comment]
Merci de ta remarque, je modifierais la conf quand je serais derrière un ordi pour clarifier :)

**Comment by bacardi55** [comment]
Fix with this commit: https://github.com/bacardi55/kalliope-wwtime/commit/92081b619f07f50b253225b648827a7ac38bfacd
