### ISSUE TITLE
Trop de mots sont dits dans la réponse de Kalliopé

### ISSUE THREAD

**Issue by tet102** [bacardi55/kalliope-wwtime#3]
Rerebonjour,
Apres install wwtime.  j'ai réussi à avoir l'heure de Lisbonne par exemple. Mais Kalliopé me réponds  "Monsieur, à est-il à Lisbonne...." aprés c'est ok.
Le fichier fr_wwtime.j2 est ok mais c'est kalliopé qui récupère des mots en trop de notre question. Quelle heure est-il à Lisbonne... Au lieu de ne garder que Lisbonne, elle prends "est-il à Lisbonne".
Avez-vous une idée pour corriger le bug svp ?

**Comment by bacardi55** [comment]
Pourrais tu partager tes fichiers de configurations (le .yml et le template) afin de voir le potentiel problème ?
l'idée etant de récupérer dans la variable uniquement le nom de la ville et de faire attention a ne pas avoir 2 synapses avec des ordres trop proches pouvant être tous les deux activés en même temps).

**Comment by tet102** [comment]
par contre, j'ai eu aussi un problème dans ton brain francais, tu as écris "Quel heure est-il ..."
Il voulait pas me reconnaitre l'odre , en fait il faut que tu corriges et que tu mettes "Quelle..."

Par contre maintenant je suis bloqué avec ordre de systemedate ? aurais-tu une idée stp. j'ai essayé différents ordres mais j'ai pas trouvé. merci

brain_fr
 - name: "Wwtime-city"
    signals:
      - order: "quelle heure est-il à {{city}}"
    neurons:
      - wwtime:
          gmaps_api_key: "API_key"
          local: "Paris France"
          city: "{{city}}"
          file_template: "templates/fr_wwtime.j2"

**Comment by bacardi55** [comment]
Le problème de l'orthographe est souvent lié au text to speech utilisé.  Google ou sphinx ne repondent pas toujours la meme chose et l'orthographe n'est pas forcément la meme entre les 2 (oui cest chiant, surtout pour les chiffres)

Je ne suis pas sur de comprendre le problème avec systemdate (j'utilise aussi les 2):
Pour le neuron systemdate, j'utilise l'ordre "Quelle heure est-il"
Alors que l'ordre pour le neuron wwtime est "donne moi l'heure de {{city}}"
afin justement d'eviter les conflits entre les 2

Cela t'aide ?

**Comment by tet102** [comment]
Ok j'ai modifié dans systemdate.yml - order: "Quelle heure est-il" sans ? sinon ordre par reconnu et dans wwtime_fr.yml   - order: "donne-moi l'heure de {{city}}"
La cela marche. merci encore

**Comment by bacardi55** [comment]
Le problème du "?" Est lie au système utilisé pour traduire l'audio en réponse texte qui diffère selon l'outil.. c'est pour ca qu'en réalité j'ai souvent plusieurs order pour une même synapse afin de palier a des changements d'orthographe venant du STT :)

Les logs d'utilisation de kalliope sont en général utiles car on peut voir ce qu'a compeis google (ou autre STT) et aussi voir si kalliope a trouvé 0, 1 ou plusieurs ordres correspond

PS: le pb etant resolu puis je fermer ce ticket ?

**Comment by tet102** [comment]
Oui merci. 
Par contre, j'installe d'autres modules. Donc je reviendrai surement vers toi désolé. Je commence à comprendre les pièges et les astuces. Je te dis pas comment cela a été dur au début. Je te remercie pour ta patience et ton aide, sincères salutations.
